
CREATE TABLE discharge_summaries (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    patient_name TEXT NOT NULL,
    discharge_date DATE NOT NULL,
    primary_diagnosis TEXT NOT NULL,
    medications TEXT,
    dietary_restrictions TEXT,
    follow_up TEXT,
    warning_signs TEXT,
    discharge_instructions TEXT
);

INSERT INTO discharge_summaries (patient_name, discharge_date, primary_diagnosis, medications, dietary_restrictions, follow_up, warning_signs, discharge_instructions) VALUES
('Alice Johnson', '2024-03-01', 'Type 2 Diabetes Mellitus', 'Metformin 500mg twice daily, Insulin Glargine 10 units nightly', 'Diabetic diet, carbohydrate controlled', 'Primary care physician in 1 week, Endocrinology in 4 weeks', 'Excessive thirst, frequent urination, blurred vision, non-healing sores', 'Monitor blood glucose four times daily, proper foot care'),
('Robert Brown', '2024-02-20', 'Congestive Heart Failure (CHF)', 'Carvedilol 6.25mg twice daily, Ramipril 5mg daily, Aspirin 81mg daily', 'Low sodium (2g/day)', 'Cardiology clinic in 10 days', 'Increased shortness of breath, sudden weight gain, increased leg swelling', 'Weigh yourself daily, limit fluid intake as directed'),
('Carol Davis', '2024-04-10', 'Pneumonia, Bacterial', 'Amoxicillin 500mg three times daily for 7 days, Ibuprofen PRN pain/fever', 'None', 'Primary care physician in 2 weeks for chest X-ray', 'Fever greater than 101.5°F, worsening cough, chest pain', 'Complete entire course of antibiotics, plenty of rest'),
('David Wilson', '2024-01-05', 'Post-Operative Hip Replacement (Left)', 'Oxycodone 5mg every 4-6 hours PRN pain, Docusate Sodium 100mg daily', 'None', 'Orthopedic surgeon in 3 weeks', 'Redness, swelling, or drainage at incision site, severe uncontrolled pain', 'Physical therapy exercises as taught, use walker/crutches as instructed, no crossing legs'),
('Eva Martinez', '2024-03-15', 'Acute Gastroenteritis', 'Ondansetron 4mg every 8 hours PRN nausea', 'BRAT diet (Bananas, Rice, Applesauce, Toast) for 48 hours', 'Primary care physician PRN if symptoms worsen', 'Inability to keep fluids down, signs of severe dehydration (dark urine, dizziness)', 'Drink clear fluids, gradually reintroduce bland foods'),
('Frank Harris', '2024-02-14', 'Myocardial Infarction (Heart Attack)', 'Clopidogrel 75mg daily, Atorvastatin 40mg nightly, Metoprolol 25mg twice daily', 'Heart-healthy, low fat, low cholesterol', 'Cardiac Rehabilitation starting next week, Cardiology in 2 weeks', 'Chest pain, radiating pain to arm/jaw, shortness of breath, dizziness', 'Do not lift more than 10 lbs, carry Nitrostat PRN chest pain'),
('Grace Lee', '2024-04-01', 'Uncontrolled Hypertension', 'Losartan 50mg daily, Hydrochlorothiazide 12.5mg daily', 'DASH diet, very low sodium', 'Primary care physician in 1 week for blood pressure check', 'Severe headache, blurred vision, nosebleed', 'Monitor blood pressure twice daily, avoid excessive salt'),
('Henry Clark', '2024-03-25', 'Asthma Exacerbation', 'Albuterol inhaler (2 puffs every 4-6 hours PRN), Prednisone 20mg daily for 5 days', 'None', 'Pulmonologist in 1 month', 'Worsening wheezing, unable to speak full sentences, blue lips/fingernails', 'Use rescue inhaler as needed, keep a symptom diary'),
('Ivy Rodriguez', '2024-01-22', 'Urinary Tract Infection (UTI), Severe', 'Ciprofloxacin 250mg twice daily for 7 days, Phenazopyridine PRN burning', 'Increase fluid intake', 'Primary care physician in 1 week for urine culture recheck', 'Fever, flank pain, vomiting, bloody urine', 'Complete entire course of antibiotics, drink cranberry juice'),
('Jack Baker', '2024-02-05', 'Atrial Fibrillation with Rapid Ventricular Response (RVR)', 'Warfarin (dose per INR protocol), Diltiazem 120mg daily', 'Consistent Vitamin K intake (for Warfarin)', 'Anticoagulation clinic in 3 days for INR check, Cardiology in 2 weeks', 'Palpitations, lightheadedness, easy bruising or bleeding', 'Know signs of bleeding, take Warfarin at the same time daily'),
('Kelly Green', '2024-04-20', 'Anxiety Disorder, Acute Episode', 'Sertraline 50mg daily, Lorazepam 0.5mg PRN anxiety/panic', 'Avoid caffeine and alcohol', 'Therapist appointment next week, Psychiatrist in 4 weeks', 'Increased feelings of despair, suicidal thoughts, inability to cope', 'Use relaxation techniques, utilize crisis hotline if needed'),
('Liam Murphy', '2024-01-30', 'Diverticulitis, Acute', 'Metronidazole 500mg three times daily for 10 days, Ciprofloxacin 500mg twice daily for 10 days', 'Clear liquid diet for 2 days, then low-fiber, then gradually high-fiber', 'Gastroenterology in 4 weeks for colonoscopy planning', 'Worsening abdominal pain, fever, chills, inability to pass gas/stool', 'Avoid seeds, nuts, and popcorn for 1 month'),
('Mia Taylor', '2024-03-08', 'Dehydration due to Hyperemesis Gravidarum (Pregnancy)', 'Pyridoxine/Doxylamine (Diclegis) as directed', 'Small, frequent meals, bland foods', 'Obstetrician in 3 days', 'Inability to keep any fluids down for over 12 hours, dark urine, significant dizziness', 'Sip on electrolyte solution frequently, rest often'),
('Noah King', '2024-02-29', 'Transient Ischemic Attack (TIA)', 'Aspirin 325mg daily, Simvastatin 20mg nightly', 'Mediterranean diet', 'Neurology in 2 weeks for carotid ultrasound review', 'Sudden weakness/numbness on one side, difficulty speaking, sudden vision loss', 'Monitor blood pressure, know the F.A.S.T. signs of stroke'),
('Olivia Perez', '2024-04-15', 'Bipolar Disorder, Manic Episode', 'Lithium Carbonate (dose per lab values), Olanzapine 5mg nightly', 'Consistent fluid and sodium intake (for Lithium)', 'Psychiatrist in 1 week, Group therapy twice weekly', 'Inability to sleep, racing thoughts, reckless behavior, increased grandiosity', 'Do not stop medications abruptly, attend all scheduled therapy'),
('Peter Scott', '2024-01-18', 'Cervical Spine Fusion (C4-C5)', 'Acetaminophen 650mg every 6 hours PRN pain, Muscle relaxant PRN muscle spasm', 'Soft diet for 3 days', 'Neurosurgeon in 4 weeks, start physical therapy in 6 weeks', 'Increased numbness or tingling in arms/hands, difficulty swallowing, fever', 'Wear cervical collar at all times except showering, no lifting'),
('Quinn White', '2024-03-20', 'Acute Bronchitis', 'Dextromethorphan/Guaifenesin PRN cough', 'None', 'Primary care physician if no improvement in 7 days', 'Cough producing bloody sputum, fever over 100.4°F', 'Increase fluid intake, use humidifier, rest'),
('Rachel Adams', '2024-02-10', 'Cellulitis (Left Lower Leg)', 'Cephalexin 500mg four times daily for 10 days', 'None', 'Wound care clinic in 3 days, Primary care physician in 10 days', 'Spreading redness, increased pain, pus drainage, fever/chills', 'Elevate left leg, keep area clean and dry, monitor redness borders'),
('Samuel Torres', '2024-04-25', 'Alcohol Withdrawal Syndrome, Mild', 'Thiamine 100mg daily, Folic Acid 1mg daily', 'Nutritious diet, avoid all alcohol', 'Addiction counseling tomorrow, Primary care physician in 3 days', 'Tremors, seizures, hallucinations, severe anxiety', 'Attend AA meetings, stay hydrated, have a support person available'),
('Tiffany Chen', '2024-01-25', 'Cholecystectomy (Gallbladder Removal)', 'Tylenol 500mg every 6 hours PRN pain', 'Low-fat diet for 6 weeks', 'Surgeon in 1 week', 'Severe abdominal pain, jaundice, fever/chills, incision site infection', 'Avoid heavy lifting, keep incision site clean, shower but do not soak'),
('Uriel Lopez', '2024-03-05', 'Spinal Stenosis', 'Gabapentin 300mg three times daily, Naproxen 500mg twice daily', 'None', 'Pain management specialist in 2 weeks, Physical therapy starting next week', 'Worsening numbness or weakness in legs, loss of bladder/bowel control', 'Apply heat/ice as needed, continue prescribed exercises'),
('Victoria Hayes', '2024-02-01', 'Hyperthyroidism Exacerbation (Graves'' Disease)', 'Methimazole 10mg daily, Propranolol 10mg three times daily', 'None, but monitor weight', 'Endocrinology in 1 week for thyroid function tests', 'Rapid heart rate, persistent fever, restlessness, unexplained weight loss', 'Take medication consistently, avoid sudden discontinuation'),
('William Foster', '2024-04-05', 'Peptic Ulcer Disease (H. pylori negative)', 'Pantoprazole 40mg daily, Sucralfate 1g four times daily', 'Avoid spicy foods, caffeine, and alcohol', 'Gastroenterology in 6 weeks for possible endoscopy', 'Bloody or black tarry stools, vomiting blood, severe persistent abdominal pain', 'Take sucralfate 30 minutes before meals and at bedtime'),
('Xena Campbell', '2024-03-30', 'Deep Vein Thrombosis (DVT) - Right Leg', 'Apixaban 5mg twice daily', 'None', 'Vascular specialist in 1 week for Doppler ultrasound', 'New or worsening leg swelling/pain, chest pain, coughing blood, sudden shortness of breath', 'Wear compression stockings, do not massage the affected leg'),
('Yusuf Naji', '2024-02-25', 'Acute Renal Failure (Post-Infectious)', 'Erythropoietin (Procrit) 10,000 units weekly (SubQ), Calcium Acetate PRN phosphate binder', 'Low potassium, low phosphate, controlled protein intake', 'Nephrology clinic in 1 week for lab work', 'Significantly decreased urine output, severe fatigue, confusion', 'Adhere strictly to fluid and dietary restrictions, take binders with meals');